### ISSUE TITLE
Existing Cluster Column Chart from beta3 stopped working in beta4

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1648] opened 2022-07-14 12:38 UTC
**Datart Version**
1.0.0b4

**Describe the bug**
An existing cluster column chart from beta 3 stopped working in beta 4. The data source is the same and both beta3 and beta4 are running in parallel for regression test. The "# Product" in the dimension is the prod_type_count field from dataset.

Manually creating the chart again in beta 4 has same issue.

**To Reproduce**

**Expected behavior**
The charts should display the same in beta 4.

**Screenshots**

Data seen from beta 3:
![image](https://user-images.githubusercontent.com/100477931/178982463-0552fdbd-5af7-4138-a72e-fd99cf0846d8.png)

Chart from beta 3:
![image](https://user-images.githubusercontent.com/100477931/178982628-d2a81504-4851-4e6b-ae9f-9e9d3b69f3b8.png)

Data seen from beta 4:
![image](https://user-images.githubusercontent.com/100477931/178982251-436157aa-a2ec-41a5-b757-185b1399549f.png)

Chart seen from beta 4:
![image](https://user-images.githubusercontent.com/100477931/178982752-87972ede-218d-45c2-8090-3ab0722f13de.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment] 2022-07-15 03:04
the issue same as `whitespace`, could you try to remove "#" mark and only keep " Products"?

**Comment by clementchong** [comment] 2022-07-15 03:45
> The issue maybe same as `whitespace` in database column name, could you try to remove "#" mark and only keep " Products"?

I tried removing the field alias but still same issue.

![image](https://user-images.githubusercontent.com/100477931/179146031-ab64619b-fd23-47ee-b7c8-4cbcaa7289e4.png)

When I try remove the prod_type from "Color" box, the chart appears but it does not provide the product split information like before.

![image](https://user-images.githubusercontent.com/100477931/179145969-6de7b2a6-1bdd-4910-85b7-e13562f77b24.png)

**Comment by Cuiyansong** [comment] 2022-07-15 03:58
I mean could you try to change "# Products" and "# Clients" to " Products" and " Clients"?

**Comment by clementchong** [comment] 2022-07-15 04:06
> I mean could you try to change "# Products" and "# Clients" to " Products" and " Clients"?

Yes of course. Removed all aliases.

![image](https://user-images.githubusercontent.com/100477931/179148244-c84d085c-cdb9-48a1-b3f3-fd90519e9bb3.png)

**Comment by clementchong** [comment] 2022-07-15 04:08
There are only 3 fields in the SQL and I can see the data but the chart is not rendering.

![image](https://user-images.githubusercontent.com/100477931/179148446-566cc4d0-ab9d-42cf-a991-e93f059f3861.png)

![image](https://user-images.githubusercontent.com/100477931/179148493-a0a4ff5e-734c-499b-b848-733f542e42f7.png)

**Comment by Cuiyansong** [comment] 2022-07-15 04:13
Sorry for misunderstanding, let me try to produce the error first.

**Comment by clementchong** [comment] 2022-07-15 04:15
ok thank you. I turned on debug but do not see SQL error, hence checking here.

**Comment by Cuiyansong** [comment] 2022-07-15 08:25
This issue will be fixed in rc.0, thanks for your contributions 👍🏿 .

**Comment by Cuiyansong** [comment] 2022-07-16 07:26
This is #790 , root cause is number value is not strict equal to string value when compare two value.

**Comment by clementchong** [comment] 2022-07-16 08:46
Ok thank you!

**Comment by Cuiyansong** [comment] 2022-07-25 02:09
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。

**Closed by Cuiyansong** 2022-07-25 02:09 UTC
Labels: bug, frontend

**Comment by clementchong** [comment] 2022-07-25 02:29
> 感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。

好的！谢谢你！
