### ISSUE TITLE
前端编译错误

### ISSUE THREAD

**Issue by caiiansheng** [running-elephant/datart#444] opened 2021-12-24 03:31 UTC
**Datart Version**
datart-1.0.0-alpha.3

**Describe the bug**
前端编译错误

**Screenshots**
![image](https://user-images.githubusercontent.com/26760483/147312376-bf62caf1-d8b2-4dad-8435-a7c14d9884bb.png)

**Additional context**
css-loader@4.3.0
postcss-loader@3.0.0
resolve-url-loader@3.1.4
craco-less@1.20.0
less-loader@7.3.0
ant-design/pro-form@1.52.2

**Comment by scottsut** [comment] 2021-12-24 04:23
Duplicate of #440

**Closed by scottsut** 2021-12-24 04:23 UTC
