### ISSUE TITLE
安装之后新增目录出现乱码

### ISSUE THREAD

**Issue by wubiaocc** [running-elephant/datart#592] opened 2022-01-12 08:34 UTC
<img width="1452" alt="WX20220112-163727@2x" src="https://user-images.githubusercontent.com/24599763/149092677-7832153c-cc5a-4d58-adc5-ff15e0d98b0b.png">

**Comment by scottsut** [comment] 2022-01-12 12:00
Duplicate of #22

**Closed by scottsut** 2022-01-12 12:00 UTC
Labels: wontfix
